name: AWS Terraform Apply

on:
  workflow_run: # This allows you to run the workflow automatically when another workflow is completed
    workflows: ["01 Terraform Validate & Plan"]
    types:
      - completed
  workflow_dispatch:  # This allows you to run the workflow manually with a button click

env:
  AWS_REGION: eu-west-2  # Change this to your desired AWS region
  SNOWFLAKE_REGION: eu-west-2  # Change this to your Account SF region

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=${{ env.AWS_REGION }}" >> $GITHUB_ENV
        echo "SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER }}" >> $GITHUB_ENV
        echo "SNOWFLAKE_AUTHENTICATOR=${{ secrets.SNOWFLAKE_AUTHENTICATOR }}" >> $GITHUB_ENV
        echo "SNOWFLAKE_PRIVATE_KEY=${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" >> $GITHUB_ENV
        echo "SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT }}" >> $GITHUB_ENV
        echo "SNOWFLAKE_REGION=${{ env.SNOWFLAKE_REGION }}" >> $GITHUB_ENV

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve