name: SnowFlake Terraform Validate & Plan

on:
  push:
    branches: # This allows you to run the workflow automatically as soon as you push to the main branch
      - main
    paths:
      - 'terraform/snowflake/**'
  workflow_dispatch:  # This allows you to run the workflow manually with a button click

env:
  SNOWFLAKE_REGION: eu-west-2  # Change this to your Account SF region

jobs:
  terraform_validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure SF credentials
      run: |
        echo "SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER }}" >> $GITHUB_ENV
        echo "SNOWFLAKE_AUTHENTICATOR=${{ secrets.SNOWFLAKE_AUTHENTICATOR }}" >> $GITHUB_ENV
        echo "SNOWFLAKE_PRIVATE_KEY=${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" >> $GITHUB_ENV
        echo "SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT }}" >> $GITHUB_ENV
        echo "SNOWFLAKE_REGION=${{ env.SNOWFLAKE_REGION }}" >> $GITHUB_ENV

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Validate
      working-directory: ./terraform/snowflake
      run: terraform validate

  terraform_plan:
    needs: terraform_validate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure SF credentials
      run: |
        echo "SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER }}" >> $GITHUB_ENV
        echo "SNOWFLAKE_AUTHENTICATOR=${{ secrets.SNOWFLAKE_AUTHENTICATOR }}" >> $GITHUB_ENV
        echo "SNOWFLAKE_PRIVATE_KEY=${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" >> $GITHUB_ENV
        echo "SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT }}" >> $GITHUB_ENV
        echo "SNOWFLAKE_REGION=${{ env.SNOWFLAKE_REGION }}" >> $GITHUB_ENV

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: ./terraform/snowflake
      id: terraform_plan_output
      run: terraform plan -detailed-exitcode
      continue-on-error: true